### PR TITLE
Fixed deserialization of query design documents

### LINKED ISSUE #239: Failure when removing design documents (for indexes)
Cloudant 2.4.1
Using a previously suggested method to list design documents : 
```java
List<String> designDocIds = database.getAllDocsRequestBuilder()
                                    .startKey("_design/")
                                    .endKey("_design0")
                                    .build()
                                    .getResponse()
                                    .getDocIds();
```

I then remove each one using : 
`DesignDocumentManager ddm = database.getDesignDocumentManager();
ddm.remove(designDocId);`

This works fine for views etc, but when it hits a DD for Indexes, I get this error : 
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 133
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:741)
	at com.cloudant.client.org.lightcouch.internal.CouchDbUtil.getResponse(CouchDbUtil.java:211)
	at com.cloudant.client.org.lightcouch.CouchDbClient.get(CouchDbClient.java:329)
	at com.cloudant.client.org.lightcouch.CouchDatabaseBase.find(CouchDatabaseBase.java:88)
	at com.cloudant.client.api.Database.find(Database.java:536)
	at com.cloudant.client.api.DesignDocumentManager.remove(DesignDocumentManager.java:154)```

### PR DESCRIPTION
**Pull request by ricellis**
## What
Fixed deserialization of query design documents

## How

Replaced `String` map/reduce fields with `JsonElement` in `DesignDocument.MapReduce` to allow for either a JSON string or JSON object to be stored as a map function.
Default for `JsonElement.toString()` is to enclose JSON string with `"` (i.e. escaped quotes `\"`) in the Java string. Added logic to remove these leading and trailing quotes from JSON string map/reduce functions (i.e. javascript language case) to maintain backwards compatibility with existing behaviour. 
Updated CHANGES.md.

## Testing

Added tests for serializing and deserializing map functions of string and object types for the javascript and query language design documents.

## Reviewers
reviewer @rhyshort
reviewer @emlaver
## Issues
Fixes #239 (part 1), part 2 was done in #242

### CODE REVIEW

**Comment by rhyshort** [comment]
+1

File: cloudant-client/src/main/java/com/cloudant/client/api/model/DesignDocument.java [hunk 1]
```diff
@@ -446,6 +457,20 @@ public String getDbCopy() {
             return dbcopy;
         }
 
+        /**
+         * @param element JSON object or string
+         * @return a string form of the object or the JSON string with leading and trailing "
+         * stripped
+         */
+        private String stringifyMRElement(JsonElement element) {
+            String s = element.toString();
```
Comment (emlaver) [inline cloudant-client/src/main/java/com/cloudant/client/api/model/DesignDocument.java]: Wouldn't this throw an exception if the element is `null`? Also, what about renaming the variable `s` to show that the variable holds the string representation of the JSON element?

Comment (ricellis) [inline cloudant-client/src/main/java/com/cloudant/client/api/model/DesignDocument.java]: Yeah there should be a `null` check, thanks. I've added it in 198ed8b.
I also reversed the checking to use `isJsonString` instead of `isJsonObject` so that we only attempt to strip quotes if we are sure it is a string, as other JSON elements would not be quoted. Even though it (at least currently) should only be an Object or a String it should be less fragile this way.
@rhyshort FYI in case you wanted to look at this change and change your +1

**Comment by rhyshort** [comment]
Still +1, although I probably should have noticed that

File: cloudant-client/src/main/java/com/cloudant/client/api/model/DesignDocument.java (hunk 1 above)
Comment (ricellis) [inline cloudant-client/src/main/java/com/cloudant/client/api/model/DesignDocument.java]: Renamed in 16aa3f8.

**Comment by emlaver** [comment]
+1
