### PR TITLE
325 url creds

### LINKED ISSUE #325: Encoded credentials provided in ClientBuilder.url() are double encoded
If encoded credentials are provided in a URL to the `ClientBuilder.url()` method they are encoded again when the CloudantClient is built, rendering them incorrect.

- CloudantClient (java-cloudant) version(s) that are affected by this issue.
    - All 2.x and possibly older

- Java version (including vendor and platform).
    - Any

- If you're using the optional okhttp dependency.
    - Yes, but independent of HTTP client.

- A small code sample that demonstrates the issue.

```java
CloudantClient c = ClientBuilder
                 .url(new URL("https://user%40:password%40@example.example"))
                 .build();
c.serverInfo();
```

### PR DESCRIPTION
**Pull request by ricellis**
## What

Prevented double encoding of URL user info when using `ClientBuilder.url()`.

## How

Added URL decoding to creds extracted from URL.
Clarified documentation on `CookieInterceptor` WRT to URL encoding of credentials.
Updated `CHANGES.md`.

## Testing

Added special character credentials tests
* Made `MockWebServer` available for all `CloudantClientTests`.
* Added new tests:
    - testUserInfoWithSpecials()
    - testUserInfoInUrlWithSpecials()

## Issues

Fixes #325

### CODE REVIEW

File: cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java [hunk 1]
```diff
@@ -364,31 +365,77 @@ public void nullPassword() throws Exception {
...
+        assertEquals("There should be a username group and a password group in the creds", 2, m
+                .groupCount());
+        assertEquals("The username should match", encodedUser, m.group(1));
+        assertEquals("The password should match", encodedPassword, m.group(2));
 
         //ensure that building a URL from it does not throw any exceptions
         new URL(c.getBaseUri().toString());
     }
 
+    private void credentialsCheck(MockWebServer mockWebServer) throws Exception {
```
Comment (tomblench) [inline cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java]: Empty method. Was it left in by mistake?

Comment (ricellis) [inline cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java]: Yes, it was. Removed in 1f7b02a.

**Comment by ricellis** [comment]
Following feedback on the related https://github.com/cloudant/sync-android/pull/439 I added some additional characters and description of the specials in 92e50d3.
