### PR TITLE
Changed CookieInterceptor to use CookieManager

### LINKED ISSUE #273: CookieInterceptor should not try to renew with invalid credentials
- CloudantClient (java-cloudant) version(s) that are affected by this issue.
    * 2.x
- Java version (including vendor and platform).
    * Any
- If you're using the optional okhttp dependency.
    * N/A
- A small code sample that demonstrates the issue.

```java
CloudantClient client = ClientBuilder.account("example")
    .username("user")
    .password("wrong")
    .build();
client.getAllDbs(); // make any request
```

Using the wrong credentials results in this log output:

>Jul 21, 2016 11:14:31 AM com.cloudant.http.interceptors.CookieInterceptor getCookie
SEVERE: Credentials are incorrect, cookie authentication will not be attempted again by this interceptor object
Jul 21, 2016 11:14:32 AM com.cloudant.http.interceptors.CookieInterceptor getCookie
SEVERE: Credentials are incorrect, cookie authentication will not be attempted again by this interceptor object

Currently the code attempts to `getCookie` as the request is made and when the response is received (for renewal scenarios). In this case since we know the credentials are wrong there is no value trying to get the cookie again in the response.

There may be some value in throwing the exception from the `CookieInterceptor` to indicate the credentials failure earlier, but since the `CookieInterceptor` is always present in the chain allowing it to cause a request to fail earlier could interfere in scenarios where it is merely a bystander to some other authentication interceptor further down the chain so this would need some careful consideration.

### LINKED ISSUE #287: CookieInterceptor -  java.lang.StringIndexOutOfBoundsException
We have our application running on IBM Bluemix Containers and after several hours (4-8hrs) we see a lot of StringIndexOutOfBoundsException.

- CloudantClient (java-cloudant) version(s) that are affected by this issue.
CloudantClient 2.5.1

- Java version (including vendor and platform).
java 1.7

- If you're using the optional okhttp dependency.
Not sure.

- A small code sample that demonstrates the issue.

[8/19/16 1:11:58:961 UTC] 000000a0 .cloud.liberty.archaius_cloudant.CloudantConfigurationSource E An exception occurred while reading from [CloudantDB:cosmos-svt-cluster_ecmconfig,cosmosci]:
java.lang.StringIndexOutOfBoundsException
    at java.lang.String.substring(String.java:1360)
    at com.cloudant.http.interceptors.CookieInterceptor.extractCookieFromHeaderValue(CookieInterceptor.java:232)
    at com.cloudant.http.interceptors.CookieInterceptor.interceptResponse(CookieInterceptor.java:99)
    at com.cloudant.http.HttpConnection.execute(HttpConnection.java:357)
    at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:475)
    at com.cloudant.client.api.CloudantClient.executeRequest(CloudantClient.java:335)
    at com.cloudant.client.internal.views.ViewRequester.executeRequestWithResponseAsJson(ViewRequester.java:34)
    at com.cloudant.client.internal.views.ViewRequester.getResponseAsJson(ViewRequester.java:28)
    at com.cloudant.client.internal.views.ViewRequestImpl.getResponse(ViewRequestImpl.java:34)
    at com.cloudant.client.internal.views.AllDocsRequestResponse.getResponse(AllDocsRequestResponse.java:44)
    at com.ibm.ecm.cloud.liberty.archaius_cloudant.CloudantConfigurationSource.loadAllProperties(CloudantConfigurationSource.java:82)
    at com.ibm.ecm.cloud.liberty.archaius_cloudant.CloudantConfigurationSource.poll(CloudantConfigurationSource.java:120)
    at com.netflix.config.AbstractPollingScheduler$1.run(AbstractPollingScheduler.java:163)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:309)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1143)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:618)
    at java.lang.Thread.run(Thread.java:785)

### PR DESCRIPTION
**Pull request by ricellis**
## What

Changed `CookieInterceptor` to use `java.net.CookieManager`

## How

The previous `CookieInterceptor` code failed to account for the possibility of multiple `Set-Cookie` headers being present in a response. It also failed to account for the possibility of multiple cookie values within a single header. Finally and most obviously from #287 it failed to check that the string parsing it was doing was safe. To avoid having to write code for all these scenarios it seemed preferable to use the `java.net.CookieManager` instead, which should be spec compliant.

* Removed our existing cookie/header parsing and used an instance of `java.net.CookieManager` instead.
* Refactored methods and error handling to work with `CookieManager` changes.
* Made the `shouldAttemptCookieRequest` atomic as it is potentially accessed by multiple `HttpConnection` instances.

## Testing

Added tests:
* HttpTest#badCredsDisablesCookie - to check that a 401 when requesting a
cookie stops any further attempts.
* HttpTest#cookieAppliedToDifferentURL - to validate that the cookie is
successfully applied to a different request URL.

Updated the `OK_COOKIE` to better match CouchDB.
Fixed assertions impacted by cookie change (optional " not present in a `CookieManager` handled cookie).

## Issues

Fixes #287 
Also fixes #273

### CODE REVIEW

**Comment by ricellis** [comment]
Reviewers can hold off on this for a little while I investigate the CI hang on Java 1.7.

File: cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java [hunk 1]
```diff
@@ -79,86 +84,109 @@ public HttpConnectionInterceptorContext interceptRequest(HttpConnectionIntercept
...
         HttpURLConnection connection = context.connection.getConnection();
 
-        if (shouldAttemptCookieRequest) {
-            if (cookie == null) {
-                cookie = getCookie(connection.getURL(), context);
+        // First time we will have no cookies
+        if (cookieManager.getCookieStore().getCookies().isEmpty() && shouldAttemptCookieRequest
+                .get()) {
+            if (!requestCookie(connection.getURL(), context)) {
+                // Requesting a cookie failed, set a flag if we failed so we won't try again
```
Comment (tomblench) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: Log a warning, "Failed to request cookie, won't attempt again"?

Comment (tomblench) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: Never mind, I see there is logging in `requestCookie`

File: cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java [hunk 2]
```diff
@@ -79,86 +84,109 @@ public HttpConnectionInterceptorContext interceptRequest(HttpConnectionIntercept
...
+                                break;
+                            default:
+                                break;
+                        }
+                    } finally {
+                        IOUtils.closeQuietly(errorStream);
+                    }
+                    if (renewCookie) {
+                        boolean success = requestCookie(connection.getURL(), context);
+                        // Don't resend request, failed to get cookie
```
Comment (tomblench) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: comment doesn't match code immediately below

File: cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java [hunk 3]
```diff
@@ -79,86 +84,109 @@ public HttpConnectionInterceptorContext interceptRequest(HttpConnectionIntercept
...
+                        if (success) {
+                            context.replayRequest = true;
+                        } else {
+                            // Didn't successfully renew, maybe creds are expired
```
Comment (tomblench) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: "expired" is confusing in the context of this comments because we think of cookies expiring. Do you mean "maybe creds are incorrect"?

File: cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java (hunk 2 above)
Comment (ricellis) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: FIxed in 4e77de7

File: cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java (hunk 3 above)
Comment (ricellis) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: The thought I had in my mind was expired in the sense of having been changed on the server since this is a renewal and they must have been valid previously if we are trying to renew, but I see your point! Fixed in b1ef8a8.

**Comment by ricellis** [comment]
@rhyshort @tomblench the tests are passing on this now, but as well as changing the tests I added some more logging so might be worth another look

**Comment by rhyshort** [comment]
+1

File: cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java [hunk 4]
```diff
@@ -316,27 +324,34 @@ public void cookieRenewal() throws Exception {
...
         // also assert that there were 3 calls
         assertEquals("The server should have received 3 requests", 3, mockWebServer
                 .getRequestCount());
 
-        mockWebServer.takeRequest(); // cookie
-        mockWebServer.takeRequest(); // actual get
-
         // this is the request that should have the new cookie.
-        RecordedRequest request = mockWebServer.takeRequest();
+        RecordedRequest request = mockWebServer.takeRequest(10, TimeUnit.SECONDS);
```
Comment (tomblench) [inline cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java]: Can we factor out all of these timeouts to a common variable if the timeout is always going to be the same?

File: cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java [hunk 5]
```diff
@@ -864,7 +879,8 @@ public void testHttpConnectionRetries() throws Exception {
     }
 
     /**
-     * Test that an IllegalArgumentException is thrown if an https proxy address is used. SSL proxies
+     * Test that an IllegalArgumentException is thrown if an https proxy address is used. SSL
```
Comment (tomblench) [inline cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java]: Formatting

File: cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java [hunk 6]
```diff
@@ -79,86 +84,123 @@ public HttpConnectionInterceptorContext interceptRequest(HttpConnectionIntercept
...
+                                    // Set the flag for deserialization
+                                    toThrow.deserialize = true;
+                                    throw toThrow;
+                                } else {
+                                    // Was expired - set boolean to renew cookie
+                                    renewCookie = true;
+                                }
+                                break;
+                            case HttpURLConnection.HTTP_UNAUTHORIZED: //401
+                                IOUtils.toString(errorStream, "UTF-8");
```
Comment (tomblench) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: Calling `toString` and throwing away the result looks odd. Presumably this is to consume the errorStream. Out of interest does findbugs warn about discarding return values?

File: cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java [hunk 7]
```diff
@@ -79,86 +84,123 @@ public HttpConnectionInterceptorContext interceptRequest(HttpConnectionIntercept
...
-                // Don't resend request, failed to get cookie
-                if (cookie != null) {
-                    context.replayRequest = true;
                 } else {
-                    context.replayRequest = false;
+                    // Store any cookies provided on the response
+                    storeCookiesFromResponse(connection);
                 }
+            } catch (IOException e) {
+                logger.log(Level.SEVERE, "Failed to get response code from request", e);
```
Comment (tomblench) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: It's possible we could have got here because we failed to read the error stream as well - I don't know if that makes the failure too verbose

File: cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java [hunk 8]
```diff
@@ -245,7 +285,33 @@ private boolean sessionHasStarted(InputStream responseStream) throws IOException
...
+        }
+    }
+
+    private String listToSemicolonSeparatedString(List<String> cookieStrings) {
+        // RFC 6265 says multiple cookie pairs should be "; " separated
+        StringBuilder builder = new StringBuilder();
+        int index = 1; // Count from 1 since we will compare to size
+        for (String cookieString : cookieStrings) {
+            builder.append(cookieString);
+            if (index != cookieStrings.size()) {
```
Comment (tomblench) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: I think you meant `index++` here?

Also do we still support java 7? Java 8 has `String.join()`

File: cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java (hunk 4 above)
Comment (ricellis) [inline cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java]: Moved into a static method and added constants in 77b429e (sadly `MockWebServer` is final so I couldn't just override `takeRequest` to always avoid tests hanging for ages).

File: cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java (hunk 5 above)
Comment (ricellis) [inline cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java]: Fixed in  7b4cc00

File: cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java (hunk 6 above)
Comment (ricellis) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: Yes, I think findbugs normally does, not sure why it didn't for this. In 632cc86 I have moved the string extraction higher up and added some logging for the value which might be useful anyway.

File: cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java (hunk 7 above)
Comment (ricellis) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: I tweaked it in 632cc86

File: cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java (hunk 8 above)
Comment (ricellis) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: Well I was counting from 1 so I didn't, but I did mean to put it at the end of the loop, so good spot. Changed to count from zero and used `index++` in the comparison in 37770a3.

Comment (ricellis) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: Oh and yes, we are still supporting Java 7 for Android.

**Comment by tomblench** [comment]
+1
