### PR TITLE
Fixed 403 null reason deserialization

### LINKED ISSUE #256: ClassCastException when extracting reason from 403 error
If a 403 is returned from the server (for example following an attempted document save) and the server JSON response contains `{"error" : "....", "reason": null}` then a `ClassCastException` is thrown:

>java.lang.ClassCastException: com.google.gson.JsonNull incompatible with com.google.gson.JsonPrimitive
	at com.google.gson.JsonObject.getAsJsonPrimitive(JsonObject.java:162)
	at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:487)
	at com.cloudant.client.org.lightcouch.CouchDbClient.executeToInputStream(CouchDbClient.java:562)
	at com.cloudant.client.org.lightcouch.CouchDbClient.executeToResponse(CouchDbClient.java:288)
	at com.cloudant.client.org.lightcouch.CouchDbClient.put(CouchDbClient.java:417)
	at com.cloudant.client.org.lightcouch.CouchDbClient.put(CouchDbClient.java:386)
	at com.cloudant.client.org.lightcouch.CouchDatabaseBase.save(CouchDatabaseBase.java:199)
	at com.cloudant.client.api.Database.save(Database.java:723)

- CloudantClient (java-cloudant) version(s) that are affected by this issue.
    * 2.1.0 - 2.4.3 inclusive
- Java version (including vendor and platform).
    * Any
- If you're using the optional okhttp dependency.
    * N/A

### PR DESCRIPTION
**Pull request by ricellis**
## What

Fixed `ClassCastException` for `{"reason": null}` `403` responses.

## How

Changed exception `error` and `reason` assigns to use `getAsString` utility method.
Added check for `JsonNull` to `getAsString` utility method.

## Testing

Added new tests for 403 with a missing or null `reason` property:
* `handleNonExpiry403NoReason`
* `handleNonExpiry403NullReason`

## Reviewers
reviewer: @brynh
reviewer @emlaver

## Issues
Fixes #256

### CODE REVIEW

File: cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java [hunk 1]
```diff
@@ -346,6 +346,70 @@ public void handleNonExpiry403() throws Exception {
...
+            CloudantClient c = CloudantClientHelper.newMockWebServerClientBuilder(mockWebServer)
+                    .username("a")
+                    .password("b")
+                    .build();
+            //the GET request will try to get a session, then perform the GET
+            //the GET will result in a 403, which should result in a CouchDbException
+            c.executeRequest(Http.GET(c.getBaseUri()));
+            fail("A 403 not due to cookie expiry should result in a CouchDbException");
+        } catch (CouchDbException e) {
+            e.printStackTrace();
```
Comment (rhyshort) [inline cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java]: Assert that the reason is `null`

File: cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java [hunk 2]
```diff
@@ -346,6 +346,70 @@ public void handleNonExpiry403() throws Exception {
...
+        }
+    }
+
+    /**
+     * * Same as {@link #handleNonExpiry403()} but with a {@code null} reason property in the JSON.
+     *
+     * @throws Exception
+     */
+    @Test
+    public void handleNonExpiry403NullReason() throws Exception {
```
Comment (brynh) [inline cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java]: To reduce code duplication, the three `handleNonExpiry403` tests could be re-written to have a single method that does basically the same thing but takes the response body as an argument (and the `reason`, assuming the suggestion from @rhyshort to add an assertion is implemented), and then each of the three tests makes a call to this method with appropriate args.

Comment (ricellis) [inline cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java]: Done in bb18e34.
I also added the 403 renewal case it was also mostly the same.

**Comment by brynh** [comment]
+1

**Comment by emlaver** [comment]
+1
