### PR TITLE
155 utf8 encoding

### LINKED ISSUE #155: IOException: too many bytes written when saving documents with special characters
Saving a document with a character like "ç" can fail in java-cloudant 2.0.0 if the default codepage is not `UTF-8`, resulting in an exception like:

>com.cloudant.client.org.lightcouch.CouchDbException: Error retrieving server response
>...
>Caused by: java.io.IOException: too many bytes written

Besides this instance caused by `HttpConnection` there are a few other places in the code base that rely on the default JVM encoding, which is not `UTF-8` on some platforms. All of these need to be fixed to use `UTF-8`.

### PR DESCRIPTION
**Pull request by ricellis**
*What*
Always specify `UTF-8` instead of using the default codepage. Fixes #155.

*How*
Find and fix all instances in the codebase that don't specify the codepage.

*Testing*
Added new test for ç, but it would only currently fail if executed on a non `UTF-8` codepage.

reviewer @tomblench 
reviewer @rhyshort

### CODE REVIEW

File: src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java [hunk 1]
```diff
@@ -161,17 +161,21 @@ private String getCookie(URL url) {
...
+
+            // only check for ok:true, https://issues.apache.org/jira/browse/COUCHDB-1356
+            // means we cannot check that the name returned is the one we sent.
+            return jsonResponse != null
+                    && jsonResponse.has("ok")
+                    && jsonResponse.get("ok").isJsonPrimitive()
+                    && jsonResponse.getAsJsonPrimitive("ok").isBoolean()
+                    && jsonResponse.getAsJsonPrimitive("ok").getAsBoolean();
+        } catch (UnsupportedEncodingException e) {
+            throw new RuntimeException(e);
```
Comment (tomblench) [inline src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: you should re-use your comment from elsewhere `//UTF-8 should be supported on all JVMs`

**Comment by tomblench** [comment]
+1 - you might want to add the comment I suggested

File: src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java (hunk 1 above)
Comment (ricellis) [inline src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: Added in 971f239

**Comment by rhyshort** [comment]
+1
