### PR TITLE
proxy support for cookie session and IAM authentication

### LINKED ISSUE #23: Change setPermissions to use _api/v2/db/<dbname>/_security insteas of /dbname/_security
Per https://github.com/cloudant/nodejs-cloudant/issues/6#issuecomment-61628907 this will handle the merging into /dbname/_security

### LINKED ISSUE #528: Can't connect to Cloudant through proxy
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
I'm calling `proxyURL` on my ClientBuilder, but it doesn't seem to be getting used.  Just getting a TimeoutException.  The same program, used in an environment where a proxy isn't needed, works great.  And that proxy (http://10.177.140.102:3128) works fine for other Java libraries I'm using.  Note this proxy does NOT require credentials be passed, so I'm not calling `proxyUser` or `proxyPassword` on the ClientBuilder.  Note the real app is an Open Liberty-based JAX-RS microservice running in the Tanzu Kubernetes Grid.  But I've reproduced the problem with the following simpler code:

```
import com.cloudant.client.api.ClientBuilder;
import com.cloudant.client.api.CloudantClient;
import com.cloudant.client.api.Database;
import java.io.InputStream;
import java.net.URL;
import java.nio.charset.StandardCharsets;

public class CloudantTest {
    public static void main(String[] arg) {
        if (arg.length == 1) {
            System.out.println(getEntryFromCloudant(arg[0]));
        } else {
            System.out.println("Usage: CloudantTest <id>");
        }
    }

    public static String getEntryFromCloudant(String id) {
        String response = null;
        try {
            String url = System.getenv("CLOUDANT_URL");
            if ((url == null) || url.isEmpty()) return "CLOUDANT_URL not set";

            String username = System.getenv("CLOUDANT_ID");
            if ((username == null) || username.isEmpty()) return "CLOUDANT_ID not set";

            String password = System.getenv("CLOUDANT_PASSWORD");
            if ((password == null) || password.isEmpty()) return "CLOUDANT_PASSWORD not set";

            String db = System.getenv("CLOUDANT_DB");
            if ((db == null) || db.isEmpty()) return "CLOUDANT_DB not set";

            ClientBuilder builder = ClientBuilder.url(new URL(url)).username(username).password(password);

            String proxy = System.getenv("CLOUDANT_PROXY");
            if ((proxy != null) && !proxy.isEmpty()) {
                System.out.println("Adding proxy");
                builder = builder.proxyURL(new URL(proxy));
            }

            CloudantClient client = builder.build();

            Database database = client.database(db, false);

            InputStream stream = database.find(id);
            response = new String(stream.readAllBytes(), StandardCharsets.UTF_8);
        } catch (Throwable t) {
            t.printStackTrace();
            response = t.getMessage();
        }
        return response;
    }
}
```
And I'm using this manifest in the "executable" jar to get the class path setup right:
```
Manifest-Version: 1.0
Class-Path: cloudant-client-2.19.2.jar cloudant-http-2.19.2.jar gson-2.8.2.jar commons-io-2.4.jar
Main-Class: CloudantTest
```
### 2. What you expected to happen
The connection to Cloudant should have gone through the proxy out to the internet and worked.  Here's the output from my test program above when I run it in an environment that doesn't need a proxy (like my laptop):

```
jalcorn@Johns-MBP-8 account % java -jar cloudantTest.jar 014aa25148df4eea85b15b3e81ce52d7              
{"_id":"014aa25148df4eea85b15b3e81ce52d7","_rev":"2-99b94bc1438706a4d92ad5611e8ffda9","owner":"Looper8","loyalty":"Basic","balance":40.01,"commissions":9.99,"free":0,"sentiment":"Unknown","nextCommission":9.99}

jalcorn@Johns-MBP-8 account % 
```

### 3. What actually happened
I get the following exception when running the above when `kubectl exec`' d into the Kubernetes pod (which needs the proxy to get out to the internet):

```
com.cloudant.client.org.lightcouch.CouchDbException: Error retrieving server response at https://878ff489-3ab9-4d2d-86db-016f19864439-bluemix.cloudantnosqldb.appdomain.cloud:443/account/0004422e801c4590bab285e31b769ea4.
        at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:632)
        at com.cloudant.client.org.lightcouch.CouchDbClient.executeToInputStream(CouchDbClient.java:648)
        at com.cloudant.client.org.lightcouch.CouchDbClient.get(CouchDbClient.java:389)
        at com.cloudant.client.org.lightcouch.CouchDatabaseBase.find(CouchDatabaseBase.java:148)
        at com.cloudant.client.api.Database.find(Database.java:839)
        at CloudantTest.getEntryFromCloudant(CloudantTest.java:44)
        at CloudantTest.main(CloudantTest.java:11)
Caused by: java.io.IOException: Failed to read server response from  https://878ff489-3ab9-4d2d-86db-016f19864439-bluemix.cloudantnosqldb.appdomain.cloud:443/_session
        at com.cloudant.http.internal.interceptors.CookieInterceptorBase.wrapIOException(CookieInterceptorBase.java:263)
        at com.cloudant.http.internal.interceptors.CookieInterceptorBase.makeSessionRequest(CookieInterceptorBase.java:164)
        at com.cloudant.http.internal.interceptors.CookieInterceptorBase.requestCookie(CookieInterceptorBase.java:100)
        at com.cloudant.http.internal.interceptors.CookieInterceptorBase.interceptRequest(CookieInterceptorBase.java:176)
        at com.cloudant.http.HttpConnection.execute(HttpConnection.java:291)
        at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:552)
        ... 6 more
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
        at com.cloudant.http.HttpConnection.execute(HttpConnection.java:317)
        at com.cloudant.http.internal.interceptors.CookieInterceptorBase.makeSessionRequest(CookieInterceptorBase.java:140)
        ... 10 more
```
## Environment details

- Version(s) that are affected by this issue.
    > 2.19.2
- Java version including vendor and platform
    > Eclipse OpenJ9 VM, version 11.0.12+7 (en_US)
- Using the optional okhttp dependency.
    > Yes

### PR DESCRIPTION
**Pull request by emlaver**
## Checklist

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](../blob/master/DCO1.1.txt)
- [ ] Added tests for code changes _or_ test/build only changes
- [x] Updated the change log file (`CHANGES.md`|`CHANGELOG.md`) _or_ test/build only changes
- [x] Completed the PR template below:

## Description
Enable proxy support for cookie session and IAM authentication.
fixes #528 

## Approach
Extend the `CookieInterceptorBase` constructor with a proxy url parameter.
Update both `IamCookieInterceptor` and `CookieInterceptor` to support new proxy url parameter during initialization.

## Testing
Manual testing against a local mock server.  The following tests passed:
1) Proxy enabled with request + session auth against local couchdb
2) Proxy enabled with request + session auth against Cloudant
3) Proxy enabled with request + IAM (only with built-in `HttpUrlConnection`) against Cloudant

### CODE REVIEW

File: cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java [hunk 1]
```diff
@@ -24,6 +24,7 @@
 import com.cloudant.client.org.lightcouch.CouchDbProperties;
 import com.cloudant.client.org.lightcouch.internal.CouchDbUtil;
 import com.cloudant.http.HttpConnectionInterceptor;
+import com.cloudant.http.HttpConnectionInterceptorContext;
```
Comment (ricellis) [inline cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java:27]: Is this needed?

File: cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java [hunk 2]
```diff
@@ -257,7 +258,7 @@ public CloudantClient build() {
 
             // Create IAM cookie interceptor and set in HttpConnection interceptors
             IamCookieInterceptor cookieInterceptor = new IamCookieInterceptor(this.iamApiKey,
-                    this.url.toString());
+                    this.url.toString(), proxyURL);
```
Comment (ricellis) [inline cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java:261]: It doesn't matter because there is no shadowing and sadly there is very little consistency in this file between using `this` or not on the instance fields, but anyway to be consistent with your `CookieInterceptor` change it might be worth adding `this`
```suggestion
                    this.url.toString(), this.proxyURL);
```

File: cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java [hunk 3]
```diff
@@ -32,9 +32,10 @@
     public static final String IAM_TOKEN_SERVER_URL_PROPERTY_KEY = "com.cloudant.client.iamserver";
     public final URL iamServerUrl;
     private final byte[] tokenRequestPayload;
+    private final URL proxyURL;
```
Comment (ricellis) [inline cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java:35]: Not needed, as it is in the `CookieInterceptorBase`

File: cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java [hunk 4]
```diff
@@ -32,9 +32,10 @@
...
 
-    public IamCookieInterceptor(String apiKey, String baseUrl) {
-        super(baseUrl, "/_iam_session", null);
+    public IamCookieInterceptor(String apiKey, String baseUrl, URL proxyURL) {
+        super(baseUrl, "/_iam_session", null, proxyURL);
```
Comment (ricellis) [inline cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java:38]: To avoid breaking compatibility I'd prefer to see this retain the original ctor and add a second ctor for the `proxyURL` case in the same way as the `CookieInterceptor`.

File: cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java [hunk 5]
```diff
@@ -52,6 +53,7 @@ public IamCookieInterceptor(String apiKey, String baseUrl) {
             //all JVMs should support UTF-8, so this should not happen
             throw new RuntimeException(e);
         }
+        this.proxyURL = proxyURL;
```
Comment (ricellis) [inline cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java:56]: Not needed, this is done in the `super`

File: cloudant-client/src/test/java/com/cloudant/tests/SessionInterceptorExpiryTests.java [hunk 6]
```diff
@@ -139,7 +139,7 @@ public void setupSessionInterceptor(boolean okUsable, String sessionPath) {
             rpInterceptor = ci;
         } else if (sessionPath.equals("/_iam_session")) {
             // Set the endpoint value before each test
-            IamCookieInterceptor ici = new IamCookieInterceptor("apikey", baseUrl);
+            IamCookieInterceptor ici = new IamCookieInterceptor("apikey", baseUrl, null);
```
Comment (ricellis) [inline cloudant-client/src/test/java/com/cloudant/tests/SessionInterceptorExpiryTests.java:142]: If you retain the original ctor as well then this change is not needed.

File: cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptor.java [hunk 7]
```diff
@@ -47,7 +48,28 @@ public CookieInterceptor(String username, String password, String baseURL) {
             this.auth = String.format("name=%s&password=%s", URLEncoder.encode(username, "UTF-8")
                     , URLEncoder.encode(password, "UTF-8"))
                     .getBytes("UTF-8");
-            ;
+        } catch (UnsupportedEncodingException e) {
```
Comment (ricellis) [inline cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptor.java:51]: this ctor should just call `this(username, password, baseURL, null)` and avoid duplicating the content.

**Review by ricellis — CHANGES_REQUESTED** [review]
Functionally it looks fine, but I've recommended some tidy up around the ctors. Also the files need copyright updates.

File: cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java (hunk 1 above)
Comment (emlaver) [reply cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java]: Removed in a1c95fad4ccf0e845fe4649613fc184c33168220

File: cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java (hunk 2 above)
Comment (emlaver) [reply cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java]: Fixed in a1c95fad4ccf0e845fe4649613fc184c33168220

File: cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java (hunk 3 above)
Comment (emlaver) [reply cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java]: Fixed in a1c95fad4ccf0e845fe4649613fc184c33168220

File: cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java (hunk 4 above)
Comment (emlaver) [reply cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java]: Fixed in a1c95fad4ccf0e845fe4649613fc184c33168220

File: cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java (hunk 5 above)
Comment (emlaver) [reply cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java]: Removed in a1c95fad4ccf0e845fe4649613fc184c33168220

File: cloudant-client/src/test/java/com/cloudant/tests/SessionInterceptorExpiryTests.java (hunk 6 above)
Comment (emlaver) [reply cloudant-client/src/test/java/com/cloudant/tests/SessionInterceptorExpiryTests.java]: Fixed in a1c95fad4ccf0e845fe4649613fc184c33168220

File: cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptor.java (hunk 7 above)
Comment (emlaver) [reply cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptor.java]: Fixed in a1c95fad4ccf0e845fe4649613fc184c33168220

**Review by ricellis — APPROVED** [review]
+1 thanks

I noticed that we aren't using `setProxyAuthentication` in the session interceptor, but any configured ProxyAuthInterceptor will already get included when we copy the interceptors. AFAICT the non-interceptor branch is defunct (for `https` proxies that never worked) so I think this is fine.

File: cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptor.java [hunk 8]
```diff
@@ -42,12 +43,25 @@
...
+    }
+
+    /**
+     * Constructs a cookie interceptor with proxy url.
+     * Credentials should be supplied not URL encoded, this class
+     * will perform the necessary URL encoding.
+     *
+     * @param username The username to use when getting the cookie (not URL encoded)
+     * @param password The password to use when getting the cookie (not URL encoded)
+     * @param baseURL  The base URL to use when constructing an `_session` request.
```
Comment (mojito317) [inline cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptor.java:56]: `@param proxyURL` is missing

File: cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptor.java [hunk 9]
```diff
@@ -42,12 +43,25 @@
      */
     public CookieInterceptor(String username, String password, String baseURL) {
         // Use form encoding for the user/pass submission
```
Comment (mojito317) [inline cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptor.java:45]: This line is not necessary here anymore.

**Review by mojito317 — APPROVED** [review]
Overall it looks good to me! I found 2 things you have missed.
