### PR TITLE
Preserve path for cookie authentication.

### LINKED ISSUE #320: CookieInterceptor doesn't work with server that uses URL path
Following on from issue #305 the `CookieInterceptor` also needs updating to handle paths on the end of a base URL pointing to the database server.

Things to fix:

1. Update `CookieInterceptor` to take a base URL.
1. Add a test to make sure the cookie handling works with a URL that includes a path
1. Fix the error message so that the formatting is correct.

- CloudantClient (java-cloudant) version(s) that are affected by this issue.
    * <= 2.6.2
- Java version (including vendor and platform).
    * Any
- If you're using the optional okhttp dependency.
    * N/A
- A small code sample that demonstrates the issue.
```java
CloudantClient client = ClientBuilder.url("http://myhost.example.com/somepath/")
        .username("user")
        .password("pass")
        .build();
client.serverVersion();
```
>Failed to get cookie from server, response code %s, cookie authentication will not be attempted again

### PR DESCRIPTION
**Pull request by rhyshort**
## What

Preserve path for cookie authentication.

## How

Modify the constructor for `CookieInterceptor` to take the URL that the client was constructed with
to use as the base URL. 

## Testing

New test `testCookieAuthWithPath` in `HTTPTest`

## Issues

Fixes #320

### CODE REVIEW

File: cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java [hunk 1]
```diff
@@ -59,23 +59,28 @@
...
         try {
+            this.sessionURL = new URL(String.format("%s/_session", baseURL));
             username = URLEncoder.encode(username, "UTF-8");
             password = URLEncoder.encode(password, "UTF-8");
             this.sessionRequestBody = String.format("name=%s&password=%s", username, password)
                     .getBytes("UTF-8");
         } catch (UnsupportedEncodingException e) {
             //all JVMs should support UTF-8, so this should not happen
             throw new RuntimeException(e);
+        } catch (MalformedURLException e) {
```
Comment (ricellis) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: We should move the existing logging for this to here and remove the other `MalformedURLException` catch.

File: cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java [hunk 2]
```diff
@@ -59,23 +59,28 @@
...
+            // this should be a valid URL since the builder is passing it in
+            throw new RuntimeException(e);
```
Comment (ricellis) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: I don't think we should throw here if we didn't before.

File: cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java (hunk 1 above)
Comment (rhyshort) [inline cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java]: removed in d4ded9b

File: cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java [hunk 3]
```diff
@@ -154,7 +157,7 @@ public void testReadBeforeExecute() throws Exception {
     @Category(RequiresCloudant.class)
     public void testCookieAuthWithoutRetry() throws IOException {
         CookieInterceptor interceptor = new CookieInterceptor(CloudantClientHelper.COUCH_USERNAME,
-                CloudantClientHelper.COUCH_PASSWORD);
+                CloudantClientHelper.COUCH_PASSWORD, dbResource.get().getDBUri().toString());
```
Comment (ricellis) [inline cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java]: This one should be `clientResource` since it is the baseURI that is needed.

File: cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java [hunk 4]
```diff
@@ -186,6 +189,23 @@ public void testCookieAuthWithoutRetry() throws IOException {
         }
     }
 
+    @Test
+    public void testCookieAuthWithPath() throws Exception {
+        MockWebServer mockWebServer = new MockWebServer();
+        mockWebServer.enqueue(new MockResponse().setResponseCode(200).setBody("{\"ok\":true," +
```
Comment (ricellis) [inline cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java]: I think we have a pre-canned OK cookie response in `MockWebServerResources.OK_COOKIE`

Comment (rhyshort) [inline cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java]: done in 7206f74

File: cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java (hunk 3 above)
Comment (rhyshort) [inline cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java]: done in 7206f74
