### PR TITLE
186 null id or rev attachments

### LINKED ISSUE #186: Defect: Cannot Save Attachment Without Revision ID
Using the latest version, it is not possible to save a new attachment with an id.

Here is the stack trace:

```
2016-01-20T16:47:34.92-0800 [App/0]      OUT java.lang.NullPointerException
2016-01-20T16:47:34.92-0800 [App/0]      OUT 	at com.cloudant.client.internal.URIBaseMethods.path(URIBaseMethods.java:37)
2016-01-20T16:47:34.92-0800 [App/0]      OUT 	at com.cloudant.client.internal.DatabaseURIHelper.revId(DatabaseURIHelper.java:179)
2016-01-20T16:47:34.92-0800 [App/0]      OUT 	at com.cloudant.client.internal.DatabaseURIHelper.attachmentUri(DatabaseURIHelper.java:160)
2016-01-20T16:47:34.92-0800 [App/0]      OUT 	at com.cloudant.client.org.lightcouch.CouchDatabaseBase.saveAttachment(CouchDatabaseBase.java:342)
2016-01-20T16:47:34.92-0800 [App/0]      OUT 	at com.cloudant.client.api.Database.saveAttachment(Database.java:960)
```

The `saveAttachment` method was called with a `null` value for the `docRev` argument, which is correct according to the JavaDoc:

    @param docRev The document revision to save the attachment under, or {@code null} when saving to a new document.

### PR DESCRIPTION
**Pull request by ricellis**
*What*
Fixes #186 regression when saving an attachment to a new document with a given ID (i.e. null revision) and makes `saveAttachment` match the API documentation.

*How*

* Clarified javadoc for the `Database.saveAttachment` with id & rev method.
* Fixed the implementation to generate a UUID instead of throwing an assertion
failure if `null` is passed as a document ID in line with the documentation.
* Added assertions to ensure that we have one of these three combinations

| docId | docRev |
|----|----|
|`null`|`null`|
|not-empty|null|
|not-empty|not-empty|

*Testing*

* New test for a generating a new document with a generated ID when using `saveAttachment`: `attachmentattachmentStandaloneNullIdNullRev`.
* New test for generating a new document with a supplied ID and an attachment: `attachmentStandaloneGivenId`.
* Three new tests for `IllegalArgumentException` cases.
    * `attachmentStandaloneNullDocNonNulLRev`
    * `attachmentStandaloneEmptyDocId`
    * `attachmentStandaloneDocIdEmptyRev`

reviewer @rhyshort 
reviewer @alfinkel

### CODE REVIEW

File: src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java [hunk 1]
```diff
@@ -338,7 +334,9 @@ public Response saveAttachment(InputStream in, String name, String contentType,
         assertNotEmpty(in, "in");
         assertNotEmpty(name, "name");
         assertNotEmpty(contentType, "ContentType");
-        assertNotEmpty(docId, "docId");
+        if (docId == null) {
+            docId = generateUUID();
+        }
```
Comment (alfinkel) [inline src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java]: What is the desired behavior if the docId is not null but is of length 0?

**Comment by rhyshort** [comment]
After change Al noted for behaviour +1

File: src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java (hunk 1 above)
Comment (ricellis) [inline src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java]: Thanks Al, that is a good spot.
I've re-added the previous behaviour for a non-null docId, i.e. verifying it is not an empty string.
Additionally I added checks to ensure that if docId has been provided that the revision is either `null` or a non-empty string (for the create and update cases respectively).
All in 3b75b3d including 3 new tests for these `IllegalArgumentException` cases.

**Comment by alfinkel** [comment]
+1
